name: Build Stock Firmware
on:
  release:
    types: [created]

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firmware
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install ESPHome
        run: |
          python -m pip install --upgrade pip
          pip install esphome

      - name: Create secrets.yaml based on Github Secrets
        run: |
          cat << 'EOF' > secrets.yaml
          wifi_ssid: ${{ secrets.WIFI_SSID }}
          wifi_password: ${{ secrets.WIFI_PASSWORD }}
          web_user: ${{ secrets.WEB_USER }}
          web_password: ${{ secrets.WEB_PASSWORD }}
          ota_password: ${{ secrets.OTA_PASSWORD }}
          EOF

      - name: Compile Release Firmware
        run: |
          esphome compile jarvis_withsecrets.yaml

          mkdir -p bin
          cp .esphome/build/fully-jarvis/.pioenvs/fully-jarvis/firmware.factory.bin bin/firmware.factory.bin
          cp .esphome/build/fully-jarvis/.pioenvs/fully-jarvis/firmware.bin bin/firmware.bin

      - name: Compile Debug Firmware
        run: |
          rm -rf .esphome/build/fully-jarvis
          esphome compile debug.yaml

          mkdir -p bin
          cp .esphome/build/fully-jarvis/.pioenvs/fully-jarvis/firmware.factory.bin bin/debug-firmware.factory.bin
          cp .esphome/build/fully-jarvis/.pioenvs/fully-jarvis/firmware.bin bin/debug-firmware.bin

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          # Note: this does NOT take the working-directory into account -_-
          path: 'firmware/bin/*.bin'
